const pricingData = [
  {
    id: 0,
    title: "Starter",
    desc: "Best for solo founders and small teams starting structured outbound.",
    price: 0.01,
    link: "/",
    benefits: [
      "150 high-quality B2B leads/month",
      "Verified decision-makers: CEOs, Founders, Managers",
      "Smart filters (industry, role, location, revenue, headcount)",
      "Contact details: email, direct dial, company info",
      "Email leads directly from your dashboard",
      "Create 3 campaigns/month",
      "Real-time status tracking (delivered, opened)",
      "Unused leads roll over to the next month",
      "Email support",
    ],
    leads: 30,
  },
  {
    id: 1,
    title: "PRO",
    desc: "For growing teams and outbound-driven businesses ready to scale outreach with precision.",
    price: 99,
    link: "/",
    color: true,
    benefits: [
      "400 high-quality, verified B2B leads/month",
      "Decision-maker contacts: CEOs, Founders, Managers, Directors",
      "Advanced filters: funding status, tech stack, employee size, location",
      "Full lead details: email, direct dial, company info, revenue, HQ address",
      "AI-powered lead scoring to prioritize top opportunities",
      "Create and schedule up to 10 email campaigns/month",
      "Real-time engagement tracking (opens, clicks)",
      "Campaign analytics & performance stats",
      "ChatGPT4",
      "Unused leads roll over to next month",
      "Priority support",
    ],
    leads: 400,
  },
  {
    id: 2,
    title: "Enterprise",
    desc: " Built for sales teams, agencies, and high-growth companies that need scale, control, and custom workflows.",
    price: 249,
    link: "/",
    benefits: [
      "800  verified decision-maker leads/month",
      "All Growth features, plus:",
      "Unlimited email campaigns",
      "Dedicated account manager for onboarding + support",
      "Team access: multi-user login and collaboration tools",
      "Slack and phone support",
    ],
    leads: 800,
  },
];

export default pricingData;
