const pricingData = [
  {
    id: 0,
    title: "PLUS",
    desc: "Perfect for solo founders or early-stage teams building outbound from scratch.",
    price: 0.01,
    annualPrice: 374,
    leads: 150,
    link: "/",
    planId: "P-74J685623B288143WNBN7CQY",
    annualPlanId: "P-83F02828AK235573YNBUPPCY",
    benefits: [
      "150 high-quality B2B leads/month",
      "Verified decision-makers: CEOs, Founders, Managers",
      "Smart filters (industry, role, location, revenue, headcount)",
      " Full contact details: email, direct dial, company info",
      "Email leads directly from your dashboard",
      "Create up to 10 campaigns/month",
      "Real-time status tracking: Delivers, Opens",
      "Dashboard analytics & activity logs",
      "Unused leads roll over to next month",
      "Email support",
    ],
  },
  {
    id: 1,
    title: "PRO",
    desc: "Ideal for growing teams and outreach-driven companies looking to scale.",
    price: 0.01,
    annualPrice: 950,
    leads: 400,
    link: "/",
    color: true,
    planId: "P-2TJ41897NU456330ANBN7EEY",
    annualPlanId: "P-1T529730KX668460NNBUPPQY",
    benefits: [
      "400 targeted B2B leads/month",
      "Decision-maker contacts: CEOs, Founders, Managers, Directors",
      "Advanced filters: funding status, tech stack, employee size, location",
      "Full lead details: email, direct dial, company info, revenue, HQ address",
      "AI-powered lead scoring & prioritization",
      "Create up to 50 campaigns/month",
      "Real-time engagement tracking",
      "Campaign analytics & performance insights",
      "ChatGPT-4 built-in for messaging",
      "Unused leads roll over",
      "Priority support",
    ],
  },
  {
    id: 2,
    title: "HYPER",
    desc: "Designed for outbound teams, agencies, and high-volume sales workflows.",
    price: 0.01,
    annualPrice: 1720,
    leads: 800,
    link: "/",
    planId: "P-3M451725FG751784VNBN7FDY",
    annualPlanId: "P-3BM54016W0125070RNBUPQFI",
    benefits: [
      "800+ verified leads/month",
      "AAll Pro features included",
      "Unlimited email campaigns",
      "Dedicated account manager for onboarding + support",
      "Multi-user/team access with collaboration tools",
      "Slack & phone support",
      "Custom onboarding workflows",
    ],
  },
];

export default pricingData;
