const regionsData = {
  "United States": ["United States"],
  Canada: ["Canada"],
  "United Kingdom": ["United Kingdom"],
  Europe: [
    "Germany",
    "Italy",
    "Spain",
    "Norway",
    "France",
    "Netherlands",
    "Switzerland",
    "Belgium",
    "Sweden",
    "Denmark",
    "Austria",
    "Poland",
    "Portugal",
    "Greece",
    "Ireland",
    "Finland",
  ],
  "Middle East": [
    "UAE",
    "Saudi Arabia",
    "Qatar",
    "Kuwait",
    "Bahrain",
    "Oman",
    "Jordan",
    "Lebanon",
    "Egypt",
  ],
  Asia: [
    "India",
    "Singapore",
    "Hong Kong",
    "Japan",
    "South Korea",
    "China",
    "Malaysia",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Philippines",
  ],
  Africa: [
    "South Africa",
    "Nigeria",
    "Kenya",
    "Egypt",
    "Morocco",
    "Ghana",
    "Tanzania",
    "Uganda",
    "Ethiopia",
    "Algeria",
  ],
};

export default regionsData;
