import "./globals.css";
import ErrorMsg from "./components/ErrorMsg";
import Footer from "./layout/footer/Footer";
import NavigationWrapper from "./layout/navigation/NavigationWrapper";
import SideBar from "./layout/navigation/side/SideBar";
import { StoreProvider } from "./lib/store/StoreProvider";
import AuthProvider from "./lib/store/AuthProvider";
import EmailModal from "./pages/emailModal/EmailModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <AuthProvider>
        <html lang="en">
          <body className="center flex-col">
            <main className="relative w-full max-w-[1650px]">
              <NavigationWrapper />
              {children}
              <ErrorMsg />
              <SideBar />
              <EmailModal />
              <Footer />
            </main>
          </body>
        </html>
      </AuthProvider>
    </StoreProvider>
  );
}
